import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "outline-variant": "var(--outline-variant)",
        "inverse-primary": "var(--inverse-primary)",
        "tertiary-container": "var(--tertiary-container)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "outline": "var(--outline)",
        "surface": "var(--surface)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "surface-container-high": "var(--surface-container-high)",
        "surface-bright": "var(--surface-bright)",
        "surface-dim": "var(--surface-dim)",
        "surface-variant": "var(--surface-variant)",
        "on-secondary": "var(--on-secondary)",
        "error-container": "var(--error-container)",
        "inverse-surface": "var(--inverse-surface)",
        "tertiary": "var(--tertiary)",
        "secondary": "var(--secondary)",
        "primary": "var(--primary)",
        "secondary-container": "var(--secondary-container)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "primary-container": "var(--primary-container)",
        "on-secondary-container": "var(--on-secondary-container)",
        "background": "var(--background)",
        "error": "var(--error)",
        "on-tertiary": "var(--on-tertiary)",
        "on-surface-variant": "var(--on-surface-variant)",
        "on-primary-container": "var(--on-primary-container)",
        "on-background": "var(--on-background)",
        "secondary-fixed": "var(--secondary-fixed)",
        "surface-container-low": "var(--surface-container-low)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "on-error-container": "var(--on-error-container)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "on-primary": "var(--on-primary)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        "surface-tint": "var(--surface-tint)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "on-error": "var(--on-error)",
        "surface-container": "var(--surface-container)",
        "on-surface": "var(--on-surface)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        // Map Shadcn base requirements
        border: "var(--outline-variant)",
        input: "var(--outline-variant)",
        ring: "var(--primary)",
        foreground: "var(--on-surface)",
        card: "var(--surface-container-lowest)",
        "card-foreground": "var(--on-surface)",
        popover: "var(--surface-container)",
        "popover-foreground": "var(--on-surface)",
      },
      fontFamily: {
        headline: ["var(--font-plus-jakarta)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
        label: ["var(--font-inter)", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;
